default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: hacker_post_development
  username: postgres
  password: "12345678"

test:
  <<: *default
  database: hacker_post_test
  username: postgres
  password: "12345678"

# Production - recommended: use ENV vars for credentials.
# If you really want to hardcode them (not recommended), uncomment the username/password lines.
production:
  primary: &primary_production
    <<: *default
    database: hacker_post_production
    # Recommended: set the username/password via environment variables instead of committing here:
    username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
    password: <%= ENV.fetch("DATABASE_PASSWORD") { "12345678" } %>
  cache:
    <<: *primary_production
    database: hacker_post_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: hacker_post_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: hacker_post_production_cable
    migrations_paths: db/cable_migrate
